version: '3'
services:
  nginx:
    ports:
      - '5000:80'
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_ROOT_PASSWORD}"
