# shared configuration file, delete port if prod and dev are different
version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '5000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_ROOT_PASSWORD}"
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
